Update quotes.ts
AnilSeervi/inspirational-quotes pull request #17
Opened 2022-10-05 17:20 UTC by Praveen007-K

### Description

### Additional context

---

### What is the purpose of this pull request? 

- [x] Add quotes
- [ ] Bug fix
- [ ] New Feature
- [ ] Add more tests
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123` or `closes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-10-05 17:39 UTC, AnilSeervi requested changes
Can you look into why the checks failed and do the needed change?
I think its the apostrophe. You need to use the "right singe quote" for the test to pass.
While you are at it, can you also move the new one to the end of the list. Thank you.

2022-10-05 17:39 UTC, AnilSeervi commented on src/quotes.ts
> +		author: `Paulo Coelho`,
By `author`, I mean the one who actually said that and not the one who quoted it @Praveen007-K

2022-10-05 17:56 UTC, Praveen007-K reviewed
Changes made

2022-10-06 14:55 UTC, AnilSeervi commented
> Changes made

I don't think the changes made any difference @Praveen007-K, the checks still seems to be failing.
Can you follow the [Contributing guidelines](https://github.com/AnilSeervi/inspirational-quotes/blob/main/CONTRIBUTING.md) properly and make the required changes

2022-10-09 16:03 UTC, AnilSeervi commented
Closing due no response.

2022-10-09 16:03 UTC, closed without merging